/** Map an OpenAPI path template (`/v1/users/{id}`) to Fastify's `:id` syntax. */
export function toFastifyPath(openapiPath: string): string {
  return openapiPath.replace(/\{([^}]+)\}/g, ":$1");
}

/** Render a TS string literal safe for emission. */
export function jsString(s: string): string {
  return JSON.stringify(s);
}

/** Pascal-case a string. */
export function pascal(s: string): string {
  const parts = s.split(/[-_.\s/]+/).filter(Boolean);
  return parts.map((p) => p[0]!.toUpperCase() + p.slice(1)).join("");
}

/** Capitalise the first letter. */
export function cap(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}

/** A `// Code generated by kdex-fnnodejsgen; DO NOT EDIT.` banner. */
export const GEN_BANNER = "// Code generated by kdex-fnnodejsgen; DO NOT EDIT.";
